<?
$PERM["index.php"]["2"]="D";
$PERM["index.php"]["5"]="D";
$PERM["index.php"]["3"]="D";
$PERM["index.php"]["4"]="D";
$PERM["index.php"]["11"]="D";
$PERM["index.php"]["8"]="D";
$PERM["index.php"]["6"]="X";
$PERM["index.php"]["10"]="X";
$PERM["index.php"]["7"]="D";
$PERM["index.php"]["*"]="D";
?>